package com.example.demo.corba;


/**
* CalculadoraApp/_CalculadoraStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/example/demo/corba/Calculadora.idl
* Segunda-feira, 25 de Agosto de 2025 14h07min44s BRT
*/

public class _CalculadoraStub extends org.omg.CORBA.portable.ObjectImpl implements Calculadora
{


  // Realiza uma operação entre dois valores
  public double calculate (double valor1, double valor2, String operacao)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("calculate", true);
                $out.write_double (valor1);
                $out.write_double (valor2);
                $out.write_string (operacao);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return calculate (valor1, valor2, operacao        );
            } finally {
                _releaseReply ($in);
            }
  } // calculate

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculadoraApp/Calculadora:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     //com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "CalculadoraApp._CalculadoraStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CalculadoraStub
