package com.example.demo.corba;


/**
* CalculadoraApp/CalculadoraPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/example/demo/corba/Calculadora.idl
* Segunda-feira, 25 de Agosto de 2025 14h07min44s BRT
*/

public abstract class CalculadoraPOA extends org.omg.PortableServer.Servant
 implements CalculadoraOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculate", 0);
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Realiza uma operação entre dois valores
       case 0:  // CalculadoraApp/Calculadora/calculate
       {
         double valor1 = in.read_double ();
         double valor2 = in.read_double ();
         String operacao = in.read_string ();
         double $result = (double)0;
         $result = this.calculate (valor1, valor2, operacao);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculadoraApp/Calculadora:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculadora _this() 
  {
    return CalculadoraHelper.narrow(
    super._this_object());
  }

  public Calculadora _this(org.omg.CORBA.ORB orb) 
  {
    return CalculadoraHelper.narrow(
    super._this_object(orb));
  }


} // class CalculadoraPOA
