package com.example.demo.corba;


/**
* CalculadoraApp/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/example/demo/corba/Calculadora.idl
* Segunda-feira, 25 de Agosto de 2025 14h07min44s BRT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
