package com.example.demo.corba;

/**
* CalculadoraApp/CalculadoraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/example/demo/corba/Calculadora.idl
* Segunda-feira, 25 de Agosto de 2025 14h07min44s BRT
*/

public final class CalculadoraHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculadora value = null;

  public CalculadoraHolder ()
  {
  }

  public CalculadoraHolder (Calculadora initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculadoraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculadoraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculadoraHelper.type ();
  }

}
