package com.example.demo.corba;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/example/demo/corba/Calculadora.idl
* Segunda-feira, 25 de Agosto de 2025 14h07min44s BRT
*/

public interface CalculadoraOperations 
{

  // Realiza uma operação entre dois valores
  double calculate (double valor1, double valor2, String operacao);
} // interface CalculadoraOperations
